### ISSUE TITLE
Cannot load a fits-file

### ISSUE THREAD

**Issue by charlyms** [fred3m/toyz#13]
If Itry to open a fits-file I get the error-message "ERROR: PYTHON ERROR:KeyError('optional',)"
What went wrong?
I have Ubuntu 64 bit
Reghards from Germany
Klaus Lang

**Comment by fred3m** [comment]
I'm not sure, this hasn't come up before. Are you able to open the image with astropy? If so, please post a printout of your terminal so I can see the traceback to try and find the error (the error and traceback should also be stored in the browser if you know how to use the web console). 

If you cannot open the image with astropy we may have to open a ticket with them, although if you can give me a link to download the image I'd be happy to try to view it on my end and see if I can replicate the error.

**Comment by charlyms** [comment]
Hello, sorry for delay.
I tried something with toyz. Unfamilar with python at all I cannot describe or even solve the problem.
My immage-source:"https://archive.stsci.edu/pub/hlsp/frontier/macs0416/images/hst/v0.5-20140110/hlsp_frontier_hst_wfc3-60mas_macs0416_f125w_v0.5-20140110_drz.fits".
The output from the console: 
kaus@kaus-virtual-machine:~/Downloads/toyz$ toyz
Loading dependencies, please wait...
Server root directory: /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz
Application root directory: /home/kaus/Downloads/toyz
Server is running on port 8888
Type CTRL-c at any time to quit the application
[I 150722 19:01:05 web:1908] 304 GET / (127.0.0.1) 110.85ms
[I 150722 19:01:05 web:1908] 304 GET /third_party/jquery/jquery.min.js (127.0.0.1) 106.40ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/toyz_core.js
permissions frwx
[I 150722 19:01:06 web:1908] 304 GET /static/web/static/toyz_core.js (127.0.0.1) 26.51ms
[I 150722 19:01:06 web:1908] 200 GET /third_party/jquery_ui/jquery-ui.js?_=1437584466059 (127.0.0.1) 54.53ms
[W 150722 19:01:06 web:1908] 404 GET /favicon.ico (127.0.0.1) 0.35ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/toyz_gui.js
permissions frwx
[I 150722 19:01:06 web:1908] 200 GET /static/web/static/toyz_gui.js?_=1437584466060 (127.0.0.1) 38.15ms
[I 150722 19:01:06 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.contextMenu.js?_=1437584466061 (127.0.0.1) 25.20ms
[I 150722 19:01:06 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.ui.position.js?_=1437584466062 (127.0.0.1) 5.20ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/settings.js
permissions frwx
[I 150722 19:01:06 web:1908] 200 GET /static/web/static/settings.js?_=1437584466063 (127.0.0.1) 23.04ms
[I 150722 19:01:06 web:1908] 304 GET /third_party/jquery_ui_themes/redmond/jquery-ui.min.css (127.0.0.1) 23.94ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/toyz.css
permissions frwx
[I 150722 19:01:06 web:1908] 304 GET /static/web/static/toyz.css (127.0.0.1) 1.71ms
[I 150722 19:01:06 web:1908] 304 GET /third_party/jquery-contextMenu/jquery.contextMenu.css (127.0.0.1) 23.33ms
[I 150722 19:01:06 web:1908] 304 GET /third_party/jquery_ui_themes/redmond/images/ui-bg_inset-hard_100_fcfdfd_1x100.png (127.0.0.1) 26.90ms
[I 150722 19:01:06 web:1908] 304 GET /third_party/jquery_ui_themes/redmond/images/ui-bg_glass_85_dfeffc_1x400.png (127.0.0.1) 1.02ms
[I 150722 19:01:06 web:1908] 304 GET /third_party/jquery_ui_themes/redmond/images/ui-bg_inset-hard_100_f5f8f9_1x100.png (127.0.0.1) 2.35ms
New session
Users logged in: ['admin']
[I 150722 19:01:07 web:1908] 304 GET /third_party/jquery_ui_themes/redmond/images/ui-bg_gloss-wave_55_5c9ccc_500x100.png (127.0.0.1) 14.09ms
[I 150722 19:01:07 web:1908] 304 GET /third_party/jquery_ui_themes/redmond/images/ui-bg_glass_75_d0e5f5_1x400.png (127.0.0.1) 20.86ms
job_process 2015-07-22__19_01_06-975110 finished
workspace path: 
path_split [u'']
path length 1
[I 150722 19:01:47 web:1908] 304 GET /workspace/ (127.0.0.1) 18.62ms
[I 150722 19:01:48 web:1908] 304 GET /third_party/jquery_ui/jquery-ui.js (127.0.0.1) 0.90ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/viewer.js
permissions frwx
[I 150722 19:01:48 web:1908] 304 GET /static/web/static/viewer.js (127.0.0.1) 28.12ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/workspace.js
permissions frwx
[I 150722 19:01:48 web:1908] 304 GET /static/web/static/workspace.js (127.0.0.1) 34.57ms
[I 150722 19:01:48 web:1908] 200 GET /third_party/jquery_ui/jquery-ui.js?_=1437584508070 (127.0.0.1) 1.88ms
[I 150722 19:01:48 web:1908] 304 GET /third_party/jquery_ui_themes/redmond/images/ui-icons_6da8d5_256x240.png (127.0.0.1) 15.59ms
[I 150722 19:01:48 web:1908] 304 GET /third_party/jquery_ui_themes/redmond/images/ui-bg_flat_0_aaaaaa_40x100.png (127.0.0.1) 3.67ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/toyz_gui.js
permissions frwx
[I 150722 19:01:48 web:1908] 200 GET /static/web/static/toyz_gui.js?_=1437584508071 (127.0.0.1) 1.05ms
New session
Users logged in: ['admin']
[I 150722 19:01:48 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.contextMenu.js?_=1437584508072 (127.0.0.1) 9.33ms
[I 150722 19:01:48 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.ui.position.js?_=1437584508073 (127.0.0.1) 0.96ms
[I 150722 19:01:49 web:1908] 304 GET /third_party/jquery_ui_themes/redmond/images/ui-icons_469bdd_256x240.png (127.0.0.1) 18.00ms
[I 150722 19:01:56 web:1908] 304 GET /third_party/jquery_ui_themes/redmond/images/ui-icons_217bc0_256x240.png (127.0.0.1) 21.08ms
[I 150722 19:03:44 web:1908] 304 GET /third_party/jquery_ui_themes/redmond/images/ui-icons_f9bd01_256x240.png (127.0.0.1) 19.74ms
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/utils/core.py", line 529, in run_job
    response = task(toyz_settings, job['id'], job['parameters'])
  File "/usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/tasks.py", line 476, in load_data_file
    user_id=tid['user_id'], data_type=data_type, paths=params['paths'])
  File "/usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/utils/sources.py", line 32, in __init__
    self.set_data(data, data_type, data_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/utils/sources.py", line 82, in set_data
    self.data = toyz.utils.io.load_data(**self.paths['data'])
  File "/usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/utils/io.py", line 666, in load_data
    load_options = params['params'].keys()+params['optional'].keys()
KeyError: 'optional'
If Iam able to the image with astropy? please look at the output from the console:
>>> hdulist = pyfits.open('hlsp_frontier_hst_wfc3-60mas_macs0416_f125w_v0.5-20140110_drz.fits')
>>> hdulist.info()
Filename: hlsp_frontier_hst_wfc3-60mas_macs0416_f125w_v0.5-20140110_drz.fits
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU     860   (5000, 5000)   float32   
1    HDRTAB      BinTableHDU    557   5R x 274C    [9A, 3A, J, D, D, D, D, D, D, D, D, D, D, D, D, J, 6A, 9A, 7A, 18A, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, J, J, D, D, D, D, D, D, J, J, 8A, 23A, 11A, 18A, 4A, D, D, J, J, D, D, D, D, 23A, D, D, D, D, J, J, D, 23A, 8A, J, D, D, D, 23A, 1A, D, D, D, D, D, D, 12A, 12A, 8A, 23A, D, D, 10A, 10A, D, D, D, 2A, 3A, 3A, 4A, 8A, 7A, D, J, D, 6A, 9A, D, D, D, 4A, 18A, 3A, J, 5A, D, D, D, 8A, D, D, D, D, D, 23A, 1A, D, 23A, D, D, D, 3A, J, 1A, 4A, D, 3A, 6A, D, D, D, D, D, 23A, D, D, D, D, D, 1A, J, J, J, J, 8A, 23A, J, J, 10A, 7A, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, 11A, D, 24A, 23A, D, 1A, 1A, D, J, D, D, 1A, 1A, D, D, D, D, D, D, D, D, D, D, D, 4A, D, J, 23A, D, 8A, D, D, 13A, D, D, J, D, D, 4A, 7A, 1A, 4A, D, 1A, J, 1A, 1A, 1A, 1A, D, D, D, D, D, D, 4A, D, D, 4A, 3A, 1A, J, 3A, 8A, J, D, D, D, 4A, J, D, D, D, J, J, J, 1A, D, D, D, D, J, J, 6A, J, 8A, D, D, 1A, 13A, J, 3A, 8A, 8A, D, J, D, 8A, 8A]   
I think yes.
Regards from Germany
Klaus Lang

**Comment by fred3m** [comment]
My apologies for the delay. I have been on vacation with my family and will remain out of town with limited connectivity until Aug 3. This appears to be a problem with my I/O API (it looks like you're trying to open a data file to plot). This is likely due to some changes I made to my API with astropy, so in the meantime if you can use astropy to save the FITS table as a csv file you should be able to open it using the pandas API in Toyz. My apologies for the bug and the delay.

**Comment by fred3m** [comment]
Thank you for your patience. I made significant updates to the part of the code that allows users to create custom data types (including astropy tables). If you update toyz and astrotoyz from their latest github versions you should now be able to view your data (I downloaded the dataset you specified and tested it).

**Comment by charlyms** [comment]
Hello,
thank you for your updates, but I still get an error.
"ERROR: PYTHON ERROR:TypeError('this constructor takes no arguments',)".
Here is the output from my terminal:
"kaus@kaus-virtual-machine:~/Downloads/toyz2/toyz/toyz$ toyz
Loading dependencies, please wait...
Server root directory: /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz
Application root directory: /home/kaus/Downloads/toyz2/toyz/toyz
Server is running on port 8888
Type CTRL-c at any time to quit the application
[I 150809 12:04:30 web:1908] 304 GET /auth/login/?next=%2F (127.0.0.1) 60.47ms
[W 150809 12:04:30 web:1908] 404 GET /favicon.ico (127.0.0.1) 0.46ms
[I 150809 12:04:34 web:1908] 302 POST /auth/login/?next=/ (127.0.0.1) 688.17ms
[I 150809 12:04:34 web:1908] 200 GET / (127.0.0.1) 16.21ms
[I 150809 12:04:34 web:1908] 200 GET /third_party/jquery_ui/jquery-ui.js?_=1439114674217 (127.0.0.1) 89.11ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/toyz_gui.js
permissions frwx
[I 150809 12:04:34 web:1908] 200 GET /static/web/static/toyz_gui.js?_=1439114674218 (127.0.0.1) 18.74ms
[I 150809 12:04:34 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.contextMenu.js?_=1439114674219 (127.0.0.1) 26.20ms
[I 150809 12:04:34 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.ui.position.js?_=1439114674220 (127.0.0.1) 25.64ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/settings.js
permissions frwx
[I 150809 12:04:34 web:1908] 200 GET /static/web/static/settings.js?_=1439114674221 (127.0.0.1) 50.26ms
New session
Users logged in: ['admin']
config path /home/kaus/Downloads/toyz2/toyz/toyz/config/toyz_config.p
config path /home/kaus/Downloads/toyz2/toyz/toyz/config/toyz_config.p
job_process 2015-08-09__12_04_35-240637 finished
[I 150809 12:05:04 web:1908] 302 POST /auth/login/?next=/ (127.0.0.1) 391.99ms
[I 150809 12:05:04 web:1908] 200 GET /auth/login/?error=Invalid+username+or+password&next=/ (127.0.0.1) 2.83ms
[I 150809 12:05:07 web:1908] 302 POST /auth/login/?next=/ (127.0.0.1) 365.02ms
[I 150809 12:05:07 web:1908] 200 GET / (127.0.0.1) 0.64ms
[I 150809 12:05:07 web:1908] 200 GET /third_party/jquery_ui/jquery-ui.js?_=1439114707513 (127.0.0.1) 1.98ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/toyz_gui.js
permissions frwx
[I 150809 12:05:07 web:1908] 200 GET /static/web/static/toyz_gui.js?_=1439114707514 (127.0.0.1) 1.20ms
[I 150809 12:05:07 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.contextMenu.js?_=1439114707515 (127.0.0.1) 1.13ms
[I 150809 12:05:07 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.ui.position.js?_=1439114707516 (127.0.0.1) 0.96ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/settings.js
permissions frwx
[I 150809 12:05:07 web:1908] 200 GET /static/web/static/settings.js?_=1439114707517 (127.0.0.1) 1.06ms
New session
Users logged in: ['admin']
job_process 2015-08-09__12_05_08-027819 finished
workspace path: 
path_split [u'']
path length 1
[I 150809 12:05:18 web:1908] 304 GET /workspace/ (127.0.0.1) 20.56ms
[I 150809 12:05:18 web:1908] 200 GET /third_party/jquery_ui/jquery-ui.js?_=1439114718375 (127.0.0.1) 1.80ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/toyz_gui.js
permissions frwx
[I 150809 12:05:18 web:1908] 200 GET /static/web/static/toyz_gui.js?_=1439114718376 (127.0.0.1) 1.17ms
New session
Users logged in: ['admin']
[I 150809 12:05:18 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.contextMenu.js?_=1439114718377 (127.0.0.1) 3.17ms
[I 150809 12:05:18 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.ui.position.js?_=1439114718378 (127.0.0.1) 1.06ms
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/utils/core.py", line 531, in run_job
    response = task(toyz_settings, job['id'], job['parameters'])
  File "/usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/tasks.py", line 506, in load_data_file
    module_info, user_id=tid['user_id'], paths=params['paths'])
TypeError: this constructor takes no arguments"
In order to guard against misunderstandings: The dataset you mentioned I tested is for me what I may call a image-fits and no fits-table. Is toyz able to open those filesat all?
Regards from Germany

**Comment by fred3m** [comment]
Ok, I think there is a misunderstanding. Currently there are two different ways to interact with data: an image viewer and a chart viewer. Since charts are generated from datasets on the server that can be linked together they are loaded as a new source. Then you can create a tile and right-click on the tile to set it's type to "Highcharts". Right-click again to edit the chart including choosing the data source and the columns to display in the chart. Note that the image you supplied does have some table information in it so this should still work (as it does for me). Make sure that you choose the correct toyz module and file type, which in this case would be "astrotoyz" and "fits" respectively.

Viewing images is a bit different. Simply right-click on the workspace and create a new tile, then resize the tile and right-click again to set the type to "Image Viewer", or in this case "Astro Viewer", which will give you some controls specific to FITS files, such as WCS. Then click on the green button with a plus sign to open a new image and set the viewer type to "large image". Now you can open your image from the dialog.

Sorry for the confusion, looks like I need to update the documentation to make this more clear.

**Comment by fred3m** [comment]
Looking back at your post I'm wondering if you were trying to link an image and a data table in a similar method to GLUE. While this is a functionality I would like to implement in the future it is currently beyond the capabilities of Toyz. In fact, at this time plots can only be linked if they are generated from the same data source, although I would also like to implement this in the future.

Thanks for the feedback.

**Comment by charlyms** [comment]
Hello,
I followed your advices and get a step further.
Now I avoid obviously error-messages and get the image-viewer to run but with no image.
Coordinates are shown but the tile keeps blank and the vierwer control missing the catalog tools.
My output from my terminal:
kaus@kaus-virtual-machine:~/Downloads/toyz2/toyz$ toyz
Loading dependencies, please wait...
Server root directory: /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz

Toyz: First Time Setup
----------------------

Create new Toyz configuration in '/home/kaus/Downloads/toyz2/toyz'? y
New toyz database created at '/home/kaus/Downloads/toyz2/toyz/db/toyz.db'
config path /home/kaus/Downloads/toyz2/toyz/config/toyz_config.p

First Time Setup completed
Application root directory: /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz
Server is running on port 8888
Type CTRL-c at any time to quit the application
[I 150811 19:06:27 web:1908] 302 GET / (127.0.0.1) 0.87ms
[I 150811 19:06:27 web:1908] 304 GET /auth/login/?next=%2F (127.0.0.1) 17.59ms
[I 150811 19:06:30 web:1908] 302 POST /auth/login/?next=/ (127.0.0.1) 369.23ms
[I 150811 19:06:30 web:1908] 200 GET / (127.0.0.1) 9.33ms
[I 150811 19:06:30 web:1908] 200 GET /third_party/jquery_ui/jquery-ui.js?_=1439312790390 (127.0.0.1) 4.79ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/toyz_gui.js
permissions frwx
[I 150811 19:06:30 web:1908] 200 GET /static/web/static/toyz_gui.js?_=1439312790391 (127.0.0.1) 1.33ms
[I 150811 19:06:30 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.contextMenu.js?_=1439312790392 (127.0.0.1) 1.18ms
[I 150811 19:06:30 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.ui.position.js?_=1439312790393 (127.0.0.1) 1.15ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/settings.js
permissions frwx
[I 150811 19:06:30 web:1908] 200 GET /static/web/static/settings.js?_=1439312790394 (127.0.0.1) 1.20ms
New session
Users logged in: ['admin']
job_process 2015-08-11__19_06_30-878198 finished
workspace path: 
path_split [u'']
path length 1
[I 150811 19:06:37 web:1908] 304 GET /workspace/ (127.0.0.1) 2.86ms
[I 150811 19:06:37 web:1908] 200 GET /third_party/jquery_ui/jquery-ui.js?_=1439312797457 (127.0.0.1) 1.73ms
parent /usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/static/toyz_gui.js
permissions frwx
[I 150811 19:06:37 web:1908] 200 GET /static/web/static/toyz_gui.js?_=1439312797458 (127.0.0.1) 1.26ms
New session
Users logged in: ['admin']
[I 150811 19:06:37 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.contextMenu.js?_=1439312797459 (127.0.0.1) 8.21ms
[I 150811 19:06:37 web:1908] 200 GET /third_party/jquery-contextMenu/jquery.ui.position.js?_=1439312797460 (127.0.0.1) 0.99ms
loading /home/kaus/Downloads/fits/STScI_POSS2UKSTU_Red_11-11-49.80_-61-18-14.fits
Detected fits image type
************************************************
viewer: {u'scale': 0.05431131019036954, 'bottom': 49, 'top': -1, u'height': 50, u'width': 50, 'right': 49, 'x_center': 24, 'left': -1, 'y_center': 24}
new tiles ['0,0']
************************************************
/usr/lib/python2.7/dist-packages/scipy/ndimage/interpolation.py:532: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
parent /home/kaus/Downloads/toyz2/toyz/users/admin/temp/2015-08-11__19_06_37-725623/images/STScI_POSS2UKSTU_Red_11-11-49_0_0_891_0_893_0.054_Spectral_2798.00_23569.00_False.png
permissions frwx
[E 150811 19:07:10 concurrent:124] Future exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/gen.py", line 230, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/web.py", line 2215, in get
        self.root, absolute_path)
      File "/usr/local/lib/python2.7/dist-packages/toyz-0.1.dev-py2.7.egg/toyz/web/app.py", line 160, in validate_absolute_path
        self, root, full_path)
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/web.py", line 2388, in validate_absolute_path
        self.path)
    HTTPError: HTTP 403: Forbidden (home/kaus/Downloads/toyz2/toyz/users/admin/temp/2015-08-11__19_06_37-725623/images/STScI_POSS2UKSTU_Red_11-11-49_0_0_891_0_893_0.054_Spectral_2798.00_23569.00_False.png is not in root static directory)
[E 150811 19:07:10 web:1496] Uncaught exception GET /file/home/kaus/Downloads/toyz2/toyz/users/admin/temp/2015-08-11__19_06_37-725623/images/STScI_POSS2UKSTU_Red_11-11-49_0_0_891_0_893_0.054_Spectral_2798.00_23569.00_False.png (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/file/home/kaus/Downloads/toyz2/toyz/users/admin/temp/2015-08-11__19_06_37-725623/images/STScI_POSS2UKSTU_Red_11-11-49_0_0_891_0_893_0.054_Spectral_2798.00_23569.00_False.png', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'de,en-US;q=0.7,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'image/png,image/*;q=0.8,*/*;q=0.5', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/workspace/', 'Cookie': 'user="2|1:0|10:1439312790|4:user|12:ImFkbWluIg==|ddf7680e6b0a9e00c0dd874a8bf66d8767885a99898cb7cee4b0ced1fbd67881"'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/web.py", line 1419, in _execute
        self.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/web.py", line 916, in finish
        self.set_etag_header()
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/web.py", line 1320, in set_etag_header
        etag = self.compute_etag()
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/web.py", line 2293, in compute_etag
        version_hash = self._get_cached_version(self.absolute_path)
    AttributeError: 'AuthStaticFileHandler' object has no attribute 'absolute_path'
[E 150811 19:07:10 web:1908] 500 GET /file/home/kaus/Downloads/toyz2/toyz/users/admin/temp/2015-08-11__19_06_37-725623/images/STScI_POSS2UKSTU_Red_11-11-49_0_0_891_0_893_0.054_Spectral_2798.00_23569.00_False.png (127.0.0.1) 5.85ms
.Can you please help again?
And please explain: is astrotoyz intgrated to toyz while it is installled?
Regards from Germany
Klaus Lang

**Comment by fred3m** [comment]
I have a guess as to what might be going on. As you noticed, astrotoyz does not automatically integrate with Toyz when it is installed. This is by design to allow users to integrate their own custom packages with Toyz. You have to follow the instructions under [Installing a Built Toyz Module](http://fred3m.github.io/toyz/custom_toyz.html) to help Toyz recognize the external module. Don't forget to restart the Toyz server after integrating astrotoyz.

Now restart the server and open a workspace in the browser. When you create a new tile you should see the following tile types when you right click on the tile: "Highcharts", "Image Viewer", "Astro Viewer." If you don't see Astro Viewer then it hasn't been integrated yet.

If this doesn't work perhaps we could setup a Skype or Google hangout so that we can work on this at the same time and I can see you screen and what you're doing. 

I appreciate your patience, I know it can be frustrating using someone else's software with documentation that hasn't properly been vetted yet. Once we get this working for you I'll be able to update the documentation so that others won't have the same trouble.

**Comment by charlyms** [comment]
Very kind of you.
I switched to Fedora and get the image viewer with 3 viewer-controls
![Uploading Arbeitsfläche 1_004.png…]()
 and toyz-template working but not astro-toys. I get the tile types ""Highcharts", "Image Viewer", Template Tile".
I would appreciate to setup a Skype hangout to get further.
Please make a proposal.
Regards from Germany
Klaus Lang

**Comment by fred3m** [comment]
I was free today but I'm busy on Thursday and Friday during the morning and
afternoon, so I'll try to upload some video tutorials on YouTube tomorrow
night that illustrate some of the basic setup features. If you're still
stuck email me (my email address is on my github profile) and I will give
you my Skype name and we can try to Skype on Monday (unless you work over
the weekend, in which case maybe Saturday morning for me, late afternoon
for you?).
